### ISSUE TITLE
Matplotlib and X-screen detached 

### ISSUE THREAD

**Issue by mikaell** [mikaell/chromograph#15]
Bug when running with detached/no X-screen:

```
cat /home/henrik.stranneheim/develop/livingox/analysis/ACC5339A2/chromograph_ar/info/chromograph_ar_ACC5339A2.2.stderr.txt
Traceback (most recent call last):
 File "/opt/conda/bin/chromograph", line 11, in <module>
   load_entry_point('chromograph', 'console_scripts', 'chromograph')()
 File "/opt/conda/share/chromograph/chromograph/chromograph.py", line 459, in main
   plot_wig(args.wigfile, args.combine, outd = args.outd, step=args.step, rgb=args.rgb)
 File "/opt/conda/share/chromograph/chromograph/chromograph.py", line 347, in plot_wig
   print_wig(df, file, outd, combine, normalize, color)
 File "/opt/conda/share/chromograph/chromograph/chromograph.py", line 354, in print_wig
   fig, ax = plt.subplots(figsize=(8, .7))
 File "/opt/conda/lib/python3.7/site-packages/matplotlib/pyplot.py", line 1209, in subplots
   fig = figure(**fig_kw)
 File "/opt/conda/lib/python3.7/site-packages/matplotlib/pyplot.py", line 545, in figure
   **kwargs)
 File "/opt/conda/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 3252, in new_figure_manager
   return cls.new_figure_manager_given_figure(num, fig)
 File "/opt/conda/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 950, in new_figure_manager_given_figure
   window = tk.Tk(className="matplotlib")
 File "/opt/conda/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
   self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:10.0"
chromograph --coverage /home/henrik.stranneheim/develop/livingox/analysis/ACC5339A2/tiddit_coverage/ACC5339A2_lanes_1234_sorted_md_brecal_tcov.wig --outd /home/henrik.stranneheim/develop/livingox/analysis/ACC5339A2/chromograph_ar/ACC5339A2_lanes_1234_sorted_md_brecal_tcov_chromograph --step 500: 1: Unknown Error - ExitCode=1```

**Comment by mikaell** [comment]
Fixed! `7a3ca82`
